const countries = [
  { label: 'Afghanistan', value: 'Afghanistan', code: 'AF', flag: '🇦🇫', dialCode: '+93' },
  { label: 'Albania', value: 'Albania', code: 'AL', flag: '🇦🇱', dialCode: '+355' },
  { label: 'Algeria', value: 'Algeria', code: 'DZ', flag: '🇩🇿', dialCode: '+213' },
  { label: 'Andorra', value: 'Andorra', code: 'AD', flag: '🇦🇩', dialCode: '+376' },
  { label: 'Angola', value: 'Angola', code: 'AO', flag: '🇦🇴', dialCode: '+244' },
  { label: 'Antigua and Barbuda', value: 'Antigua and Barbuda', code: 'AG', flag: '🇦🇬', dialCode: '+1-268' },
  { label: 'Argentina', value: 'Argentina', code: 'AR', flag: '🇦🇷', dialCode: '+54' },
  { label: 'Armenia', value: 'Armenia', code: 'AM', flag: '🇦🇲', dialCode: '+374' },
  { label: 'Australia', value: 'Australia', code: 'AU', flag: '🇦🇺', dialCode: '+61' },
  { label: 'Austria', value: 'Austria', code: 'AT', flag: '🇦🇹', dialCode: '+43' },
  { label: 'Azerbaijan', value: 'Azerbaijan', code: 'AZ', flag: '🇦🇿', dialCode: '+994' },
  { label: 'Bahamas', value: 'Bahamas', code: 'BS', flag: '🇧🇸', dialCode: '+1-242' },
  { label: 'Bahrain', value: 'Bahrain', code: 'BH', flag: '🇧🇭', dialCode: '+973' },
  { label: 'Bangladesh', value: 'Bangladesh', code: 'BD', flag: '🇧🇩', dialCode: '+880' },
  { label: 'Barbados', value: 'Barbados', code: 'BB', flag: '🇧🇧', dialCode: '+1-246' },
  { label: 'Belarus', value: 'Belarus', code: 'BY', flag: '🇧🇾', dialCode: '+375' },
  { label: 'Belgium', value: 'Belgium', code: 'BE', flag: '🇧🇪', dialCode: '+32' },
  { label: 'Belize', value: 'Belize', code: 'BZ', flag: '🇧🇿', dialCode: '+501' },
  { label: 'Benin', value: 'Benin', code: 'BJ', flag: '🇧🇯', dialCode: '+229' },
  { label: 'Bhutan', value: 'Bhutan', code: 'BT', flag: '🇧🇹', dialCode: '+975' },
  { label: 'Bolivia', value: 'Bolivia', code: 'BO', flag: '🇧🇴', dialCode: '+591' },
  { label: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina', code: 'BA', flag: '🇧🇦', dialCode: '+387' },
  { label: 'Botswana', value: 'Botswana', code: 'BW', flag: '🇧🇼', dialCode: '+267' },
  { label: 'Brazil', value: 'Brazil', code: 'BR', flag: '🇧🇷', dialCode: '+55' },
  { label: 'Brunei', value: 'Brunei', code: 'BN', flag: '🇧🇳', dialCode: '+673' },
  { label: 'Bulgaria', value: 'Bulgaria', code: 'BG', flag: '🇧🇬', dialCode: '+359' },
  { label: 'Burkina Faso', value: 'Burkina Faso', code: 'BF', flag: '🇧🇫', dialCode: '+226' },
  { label: 'Burundi', value: 'Burundi', code: 'BI', flag: '🇧🇮', dialCode: '+257' },
  { label: 'Cambodia', value: 'Cambodia', code: 'KH', flag: '🇰🇭', dialCode: '+855' },
  { label: 'Cameroon', value: 'Cameroon', code: 'CM', flag: '🇨🇲', dialCode: '+237' },
  { label: 'Canada', value: 'Canada', code: 'CA', flag: '🇨🇦', dialCode: '+1' },
  { label: 'Cape Verde', value: 'Cape Verde', code: 'CV', flag: '🇨🇻', dialCode: '+238' },
  { label: 'Central African Republic', value: 'Central African Republic', code: 'CF', flag: '🇨🇫', dialCode: '+236' },
  { label: 'Chad', value: 'Chad', code: 'TD', flag: '🇹🇩', dialCode: '+235' },
  { label: 'Chile', value: 'Chile', code: 'CL', flag: '🇨🇱', dialCode: '+56' },
  { label: 'China', value: 'China', code: 'CN', flag: '🇨🇳', dialCode: '+86' },
  { label: 'Colombia', value: 'Colombia', code: 'CO', flag: '🇨🇴', dialCode: '+57' },
  { label: 'Comoros', value: 'Comoros', code: 'KM', flag: '🇰🇲', dialCode: '+269' },
  { label: 'Congo (Brazzaville)', value: 'Congo (Brazzaville)', code: 'CG', flag: '🇨🇬', dialCode: '+242' },
  { label: 'Congo (Kinshasa)', value: 'Congo (Kinshasa)', code: 'CD', flag: '🇨🇩', dialCode: '+243' },
  { label: 'Costa Rica', value: 'Costa Rica', code: 'CR', flag: '🇨🇷', dialCode: '+506' },
  { label: 'Croatia', value: 'Croatia', code: 'HR', flag: '🇭🇷', dialCode: '+385' },
  { label: 'Cuba', value: 'Cuba', code: 'CU', flag: '🇨🇺', dialCode: '+53' },
  { label: 'Cyprus', value: 'Cyprus', code: 'CY', flag: '🇨🇾', dialCode: '+357' },
  { label: 'Czechia', value: 'Czechia', code: 'CZ', flag: '🇨🇿', dialCode: '+420' },
  { label: 'Denmark', value: 'Denmark', code: 'DK', flag: '🇩🇰', dialCode: '+45' },
  { label: 'Djibouti', value: 'Djibouti', code: 'DJ', flag: '🇩🇯', dialCode: '+253' },
  { label: 'Dominica', value: 'Dominica', code: 'DM', flag: '🇩🇲', dialCode: '+1-767' },
  { label: 'Dominican Republic', value: 'Dominican Republic', code: 'DO', flag: '🇩🇴', dialCode: '+1-809' },
  { label: 'Ecuador', value: 'Ecuador', code: 'EC', flag: '🇪🇨', dialCode: '+593' },
  { label: 'Egypt', value: 'Egypt', code: 'EG', flag: '🇪🇬', dialCode: '+20' },
  { label: 'El Salvador', value: 'El Salvador', code: 'SV', flag: '🇸🇻', dialCode: '+503' },
  { label: 'Equatorial Guinea', value: 'Equatorial Guinea', code: 'GQ', flag: '🇬🇶', dialCode: '+240' },
  { label: 'Eritrea', value: 'Eritrea', code: 'ER', flag: '🇪🇷', dialCode: '+291' },
  { label: 'Estonia', value: 'Estonia', code: 'EE', flag: '🇪🇪', dialCode: '+372' },
  { label: 'Ethiopia', value: 'Ethiopia', code: 'ET', flag: '🇪🇹', dialCode: '+251' },
  { label: 'Fiji', value: 'Fiji', code: 'FJ', flag: '🇫🇯', dialCode: '+679' },
  { label: 'Finland', value: 'Finland', code: 'FI', flag: '🇫🇮', dialCode: '+358' },
  { label: 'France', value: 'France', code: 'FR', flag: '🇫🇷', dialCode: '+33' },
  { label: 'Gabon', value: 'Gabon', code: 'GA', flag: '🇬🇦', dialCode: '+241' },
  { label: 'Gambia', value: 'Gambia', code: 'GM', flag: '🇬🇲', dialCode: '+220' },
  { label: 'Georgia', value: 'Georgia', code: 'GE', flag: '🇬🇪', dialCode: '+995' },
  { label: 'Germany', value: 'Germany', code: 'DE', flag: '🇩🇪', dialCode: '+49' },
  { label: 'Ghana', value: 'Ghana', code: 'GH', flag: '🇬🇭', dialCode: '+233' },
  { label: 'Greece', value: 'Greece', code: 'GR', flag: '🇬🇷', dialCode: '+30' },
  { label: 'Grenada', value: 'Grenada', code: 'GD', flag: '🇬🇩', dialCode: '+1-473' },
  { label: 'Guatemala', value: 'Guatemala', code: 'GT', flag: '🇬🇹', dialCode: '+502' },
  { label: 'Guinea', value: 'Guinea', code: 'GN', flag: '🇬🇳', dialCode: '+224' },
  { label: 'Guinea-Bissau', value: 'Guinea-Bissau', code: 'GW', flag: '🇬🇼', dialCode: '+245' },
  { label: 'Guyana', value: 'Guyana', code: 'GY', flag: '🇬🇾', dialCode: '+592' },
  { label: 'Haiti', value: 'Haiti', code: 'HT', flag: '🇭🇹', dialCode: '+509' },
  { label: 'Honduras', value: 'Honduras', code: 'HN', flag: '🇭🇳', dialCode: '+504' },
  { label: 'Hungary', value: 'Hungary', code: 'HU', flag: '🇭🇺', dialCode: '+36' },
  { label: 'Iceland', value: 'Iceland', code: 'IS', flag: '🇮🇸', dialCode: '+354' },
  { label: 'India', value: 'India', code: 'IN', flag: '🇮🇳', dialCode: '+91' },
  { label: 'Indonesia', value: 'Indonesia', code: 'ID', flag: '🇮🇩', dialCode: '+62' },
  { label: 'Iran', value: 'Iran', code: 'IR', flag: '🇮🇷', dialCode: '+98' },
  { label: 'Iraq', value: 'Iraq', code: 'IQ', flag: '🇮🇶', dialCode: '+964' },
  { label: 'Ireland', value: 'Ireland', code: 'IE', flag: '🇮🇪', dialCode: '+353' },
  { label: 'Israel', value: 'Israel', code: 'IL', flag: '🇮🇱', dialCode: '+972' },
  { label: 'Italy', value: 'Italy', code: 'IT', flag: '🇮🇹', dialCode: '+39' },
  { label: 'Jamaica', value: 'Jamaica', code: 'JM', flag: '🇯🇲', dialCode: '+1-876' },
  { label: 'Japan', value: 'Japan', code: 'JP', flag: '🇯🇵', dialCode: '+81' },
  { label: 'Jordan', value: 'Jordan', code: 'JO', flag: '🇯🇴', dialCode: '+962' },
  { label: 'Kazakhstan', value: 'Kazakhstan', code: 'KZ', flag: '🇰🇿', dialCode: '+7' },
  { label: 'Kenya', value: 'Kenya', code: 'KE', flag: '🇰🇪', dialCode: '+254' },
  { label: 'Kiribati', value: 'Kiribati', code: 'KI', flag: '🇰🇮', dialCode: '+686' },
  { label: 'Kuwait', value: 'Kuwait', code: 'KW', flag: '🇰🇼', dialCode: '+965' },
  { label: 'Kyrgyzstan', value: 'Kyrgyzstan', code: 'KG', flag: '🇰🇬', dialCode: '+996' },
  { label: 'Laos', value: 'Laos', code: 'LA', flag: '🇱🇦', dialCode: '+856' },
  { label: 'Latvia', value: 'Latvia', code: 'LV', flag: '🇱🇻', dialCode: '+371' },
  { label: 'Lebanon', value: 'Lebanon', code: 'LB', flag: '🇱🇧', dialCode: '+961' },
  { label: 'Lesotho', value: 'Lesotho', code: 'LS', flag: '🇱🇸', dialCode: '+266' },
  { label: 'Liberia', value: 'Liberia', code: 'LR', flag: '🇱🇷', dialCode: '+231' },
  { label: 'Libya', value: 'Libya', code: 'LY', flag: '🇱🇾', dialCode: '+218' },
  { label: 'Liechtenstein', value: 'Liechtenstein', code: 'LI', flag: '🇱🇮', dialCode: '+423' },
  { label: 'Lithuania', value: 'Lithuania', code: 'LT', flag: '🇱🇹', dialCode: '+370' },
  { label: 'Luxembourg', value: 'Luxembourg', code: 'LU', flag: '🇱🇺', dialCode: '+352' },
  { label: 'Madagascar', value: 'Madagascar', code: 'MG', flag: '🇲🇬', dialCode: '+261' },
  { label: 'Malawi', value: 'Malawi', code: 'MW', flag: '🇲🇼', dialCode: '+265' },
  { label: 'Malaysia', value: 'Malaysia', code: 'MY', flag: '🇲🇾', dialCode: '+60' },
  { label: 'Maldives', value: 'Maldives', code: 'MV', flag: '🇲🇻', dialCode: '+960' },
  { label: 'Mali', value: 'Mali', code: 'ML', flag: '🇲🇱', dialCode: '+223' },
  { label: 'Malta', value: 'Malta', code: 'MT', flag: '🇲🇹', dialCode: '+356' },
  { label: 'Marshall Islands', value: 'Marshall Islands', code: 'MH', flag: '🇲🇭', dialCode: '+692' },
  { label: 'Mauritania', value: 'Mauritania', code: 'MR', flag: '🇲🇷', dialCode: '+222' },
  { label: 'Mauritius', value: 'Mauritius', code: 'MU', flag: '🇲🇺', dialCode: '+230' },
  { label: 'Mexico', value: 'Mexico', code: 'MX', flag: '🇲🇽', dialCode: '+52' },
  { label: 'Micronesia', value: 'Micronesia', code: 'FM', flag: '🇫🇲', dialCode: '+691' },
  { label: 'Moldova', value: 'Moldova', code: 'MD', flag: '🇲🇩', dialCode: '+373' },
  { label: 'Monaco', value: 'Monaco', code: 'MC', flag: '🇲🇨', dialCode: '+377' },
  { label: 'Mongolia', value: 'Mongolia', code: 'MN', flag: '🇲🇳', dialCode: '+976' },
  { label: 'Montenegro', value: 'Montenegro', code: 'ME', flag: '🇲🇪', dialCode: '+382' },
  { label: 'Morocco', value: 'Morocco', code: 'MA', flag: '🇲🇦', dialCode: '+212' },
  { label: 'Mozambique', value: 'Mozambique', code: 'MZ', flag: '🇲🇿', dialCode: '+258' },
  { label: 'Myanmar', value: 'Myanmar', code: 'MM', flag: '🇲🇲', dialCode: '+95' },
  { label: 'Namibia', value: 'Namibia', code: 'NA', flag: '🇳🇦', dialCode: '+264' },
  { label: 'Nauru', value: 'Nauru', code: 'NR', flag: '🇳🇷', dialCode: '+674' },
  { label: 'Nepal', value: 'Nepal', code: 'NP', flag: '🇳🇵', dialCode: '+977' },
  { label: 'Netherlands', value: 'Netherlands', code: 'NL', flag: '🇳🇱', dialCode: '+31' },
  { label: 'New Zealand', value: 'New Zealand', code: 'NZ', flag: '🇳🇿', dialCode: '+64' },
  { label: 'Nicaragua', value: 'Nicaragua', code: 'NI', flag: '🇳🇮', dialCode: '+505' },
  { label: 'Niger', value: 'Niger', code: 'NE', flag: '🇳🇪', dialCode: '+227' },
  { label: 'Nigeria', value: 'Nigeria', code: 'NG', flag: '🇳🇬', dialCode: '+234' },
  { label: 'North Korea', value: 'North Korea', code: 'KP', flag: '🇰🇵', dialCode: '+850' },
  { label: 'North Macedonia', value: 'North Macedonia', code: 'MK', flag: '🇲🇰', dialCode: '+389' },
  { label: 'Norway', value: 'Norway', code: 'NO', flag: '🇳🇴', dialCode: '+47' },
  { label: 'Oman', value: 'Oman', code: 'OM', flag: '🇴🇲', dialCode: '+968' },
  { label: 'Pakistan', value: 'Pakistan', code: 'PK', flag: '🇵🇰', dialCode: '+92' },
  { label: 'Palau', value: 'Palau', code: 'PW', flag: '🇵🇼', dialCode: '+680' },
  { label: 'Palestine', value: 'Palestine', code: 'PS', flag: '🇵🇸', dialCode: '+970' },
  { label: 'Panama', value: 'Panama', code: 'PA', flag: '🇵🇦', dialCode: '+507' },
  { label: 'Papua New Guinea', value: 'Papua New Guinea', code: 'PG', flag: '🇵🇬', dialCode: '+675' },
  { label: 'Paraguay', value: 'Paraguay', code: 'PY', flag: '🇵🇾', dialCode: '+595' },
  { label: 'Peru', value: 'Peru', code: 'PE', flag: '🇵🇪', dialCode: '+51' },
  { label: 'Philippines', value: 'Philippines', code: 'PH', flag: '🇵🇭', dialCode: '+63' },
  { label: 'Poland', value: 'Poland', code: 'PL', flag: '🇵🇱', dialCode: '+48' },
  { label: 'Portugal', value: 'Portugal', code: 'PT', flag: '🇵🇹', dialCode: '+351' },
  { label: 'Qatar', value: 'Qatar', code: 'QA', flag: '🇶🇦', dialCode: '+974' },
  { label: 'Romania', value: 'Romania', code: 'RO', flag: '🇷🇴', dialCode: '+40' },
  { label: 'Russia', value: 'Russia', code: 'RU', flag: '🇷🇺', dialCode: '+7' },
  { label: 'Rwanda', value: 'Rwanda', code: 'RW', flag: '🇷🇼', dialCode: '+250' },
  { label: 'Saint Kitts and Nevis', value: 'Saint Kitts and Nevis', code: 'KN', flag: '🇰🇳', dialCode: '+1-869' },
  { label: 'Saint Lucia', value: 'Saint Lucia', code: 'LC', flag: '🇱🇨', dialCode: '+1-758' },
  { label: 'Saint Vincent and the Grenadines', value: 'Saint Vincent and the Grenadines', code: 'VC', flag: '🇻🇨', dialCode: '+1-784' },
  { label: 'Samoa', value: 'Samoa', code: 'WS', flag: '🇼🇸', dialCode: '+685' },
  { label: 'San Marino', value: 'San Marino', code: 'SM', flag: '🇸🇲', dialCode: '+378' },
  { label: 'Sao Tome and Principe', value: 'Sao Tome and Principe', code: 'ST', flag: '🇸🇹', dialCode: '+239' },
  { label: 'Saudi Arabia', value: 'Saudi Arabia', code: 'SA', flag: '🇸🇦', dialCode: '+966' },
  { label: 'Senegal', value: 'Senegal', code: 'SN', flag: '🇸🇳', dialCode: '+221' },
  { label: 'Serbia', value: 'Serbia', code: 'RS', flag: '🇷🇸', dialCode: '+381' },
  { label: 'Seychelles', value: 'Seychelles', code: 'SC', flag: '🇸🇨', dialCode: '+248' },
  { label: 'Sierra Leone', value: 'Sierra Leone', code: 'SL', flag: '🇸🇱', dialCode: '+232' },
  { label: 'Singapore', value: 'Singapore', code: 'SG', flag: '🇸🇬', dialCode: '+65' },
  { label: 'Slovakia', value: 'Slovakia', code: 'SK', flag: '🇸🇰', dialCode: '+421' },
  { label: 'Slovenia', value: 'Slovenia', code: 'SI', flag: '🇸🇮', dialCode: '+386' },
  { label: 'Solomon Islands', value: 'Solomon Islands', code: 'SB', flag: '🇸🇧', dialCode: '+677' },
  { label: 'Somalia', value: 'Somalia', code: 'SO', flag: '🇸🇴', dialCode: '+252' },
  { label: 'South Africa', value: 'South Africa', code: 'ZA', flag: '🇿🇦', dialCode: '+27' },
  { label: 'South Korea', value: 'South Korea', code: 'KR', flag: '🇰🇷', dialCode: '+82' },
  { label: 'South Sudan', value: 'South Sudan', code: 'SS', flag: '🇸🇸', dialCode: '+211' },
  { label: 'Spain', value: 'Spain', code: 'ES', flag: '🇪🇸', dialCode: '+34' },
  { label: 'Sri Lanka', value: 'Sri Lanka', code: 'LK', flag: '🇱🇰', dialCode: '+94' },
  { label: 'Sudan', value: 'Sudan', code: 'SD', flag: '🇸🇩', dialCode: '+249' },
  { label: 'Suriname', value: 'Suriname', code: 'SR', flag: '🇸🇷', dialCode: '+597' },
  { label: 'Sweden', value: 'Sweden', code: 'SE', flag: '🇸🇪', dialCode: '+46' },
  { label: 'Switzerland', value: 'Switzerland', code: 'CH', flag: '🇨🇭', dialCode: '+41' },
  { label: 'Syria', value: 'Syria', code: 'SY', flag: '🇸🇾', dialCode: '+963' },
  { label: 'Tajikistan', value: 'Tajikistan', code: 'TJ', flag: '🇹🇯', dialCode: '+992' },
  { label: 'Tanzania', value: 'Tanzania', code: 'TZ', flag: '🇹🇿', dialCode: '+255' },
  { label: 'Thailand', value: 'Thailand', code: 'TH', flag: '🇹🇭', dialCode: '+66' },
  { label: 'Timor-Leste', value: 'Timor-Leste', code: 'TL', flag: '🇹🇱', dialCode: '+670' },
  { label: 'Togo', value: 'Togo', code: 'TG', flag: '🇹🇬', dialCode: '+228' },
  { label: 'Tonga', value: 'Tonga', code: 'TO', flag: '🇹🇴', dialCode: '+676' },
  { label: 'Trinidad and Tobago', value: 'Trinidad and Tobago', code: 'TT', flag: '🇹🇹', dialCode: '+1-868' },
  { label: 'Tunisia', value: 'Tunisia', code: 'TN', flag: '🇹🇳', dialCode: '+216' },
  { label: 'Turkey', value: 'Turkey', code: 'TR', flag: '🇹🇷', dialCode: '+90' },
  { label: 'Turkmenistan', value: 'Turkmenistan', code: 'TM', flag: '🇹🇲', dialCode: '+993' },
  { label: 'Tuvalu', value: 'Tuvalu', code: 'TV', flag: '🇹🇻', dialCode: '+688' },
  { label: 'Uganda', value: 'Uganda', code: 'UG', flag: '🇺🇬', dialCode: '+256' },
  { label: 'Ukraine', value: 'Ukraine', code: 'UA', flag: '🇺🇦', dialCode: '+380' },
  { label: 'United Arab Emirates', value: 'United Arab Emirates', code: 'AE', flag: '🇦🇪', dialCode: '+971' },
  { label: 'United Kingdom', value: 'United Kingdom', code: 'GB', flag: '🇬🇧', dialCode: '+44' },
  { label: 'United States', value: 'United States', code: 'US', flag: '🇺🇸', dialCode: '+1' },
  { label: 'Uruguay', value: 'Uruguay', code: 'UY', flag: '🇺🇾', dialCode: '+598' },
  { label: 'Uzbekistan', value: 'Uzbekistan', code: 'UZ', flag: '🇺🇿', dialCode: '+998' },
  { label: 'Vanuatu', value: 'Vanuatu', code: 'VU', flag: '🇻🇺', dialCode: '+678' },
  { label: 'Vatican City', value: 'Vatican City', code: 'VA', flag: '🇻🇦', dialCode: '+379' },
  { label: 'Venezuela', value: 'Venezuela', code: 'VE', flag: '🇻🇪', dialCode: '+58' },
  { label: 'Vietnam', value: 'Vietnam', code: 'VN', flag: '🇻🇳', dialCode: '+84' },
  { label: 'Yemen', value: 'Yemen', code: 'YE', flag: '🇾🇪', dialCode: '+967' },
  { label: 'Zambia', value: 'Zambia', code: 'ZM', flag: '🇿🇲', dialCode: '+260' },
  { label: 'Zimbabwe', value: 'Zimbabwe', code: 'ZW', flag: '🇿🇼', dialCode: '+263' },
];

export default countries;
